apiVersion: v1
kind: Service
metadata:
    name: user-srv
    labels:
        app: user
spec:
    ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: user
    selector:
        app: user